name: Android

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build debug APK
        run: flutter build apk --split-per-abi --debug --dart-define=DROPBOX_APP_KEY=${{ secrets.DROPBOX_APP_KEY }}

      - name: Upload debug APKs
        uses: actions/upload-artifact@v6
        with:
          name: debug-apks
          path: build/app/outputs/flutter-apk/*-debug.apk

      - name: Build release-unsigned APK
        run: flutter build apk --split-per-abi --release --dart-define=DROPBOX_APP_KEY=${{ secrets.DROPBOX_APP_KEY }}

      - name: Upload release APKs
        uses: actions/upload-artifact@v6
        with:
          name: release-unsigned-apks
          path: build/app/outputs/flutter-apk/*-release.apk
